tinyMCE.addI18n('fr.link2post',{
linkPost:"Lier un article",
linkPage:"Lier une page",
link_a_page:"Lier une page",
show_filters:"Monter le filtre",
filter_pages:"Filtrer les pages",
content:"Contenu :",
in_title:"dans le titre",
in_content:"dans le contenu",
in_both:"les deux",
search:"Rechercher",
cancel:"Annuler",
hide_filters:"Cacher le filtre",
page:"page",
pages:"pages",
no_page:"Aucune page",
link_a_post:"Lier un article",
filter_posts:"Filtrer les articles",
all_categories:"toutes les cat\u00E9gories",
post:"article",
posts:"articles",
no_post:"Acun article"
});